### ISSUE TITLE
Wrong local header signature

### ISSUE THREAD

**Issue by momo-the-monster** [emanzione/PATCH#43]
I'm getting this error when running a WPF updater for a Unity app:

`2021-09-22 15:00:20.965 -07:00 [INF] Updating process STARTED!
2021-09-22 15:00:21.704 -07:00 [INF] Update context initializing...
2021-09-22 15:00:21.706 -07:00 [INF] Update context points to [REDACTED]
2021-09-22 15:00:21.708 -07:00 [INF] Retrieved current version: 0.1.10
2021-09-22 15:00:21.712 -07:00 [INF] Workspace cleaned. Removed 0 files
2021-09-22 15:00:21.962 -07:00 [INF] Collected 205 local files.
2021-09-22 15:00:22.156 -07:00 [INF] Retrieved definition for 0.1.10
2021-09-22 15:00:22.275 -07:00 [INF] Found 1 applicable updates.
2021-09-22 15:00:22.276 -07:00 [INF] Update context completed initialization.
2021-09-22 15:00:22.280 -07:00 [INF] Launcher update started. The update contains 1 operations.
2021-09-22 15:00:22.283 -07:00 [INF] Launcher update completed.
2021-09-22 15:00:22.284 -07:00 [INF] Repairing process started.
2021-09-22 15:00:22.287 -07:00 [INF] Repairing process completed. Checked 201 files, repaired 0 files, skipped 201 files.
2021-09-22 15:00:22.288 -07:00 [INF] Update process started.
2021-09-22 15:00:22.288 -07:00 [INF] Applying update 0.1.10_0.1.12 [ApXw6Zygo9kmkNxuVfg0vWdoPVE]
2021-09-22 15:00:22.810 -07:00 [ERR] Updating process FAILED! - Wrong local header signature @3 -    at ICSharpCode.SharpZipLib.Zip.ZipFile.TestLocalHeader(ZipEntry entry, HeaderTest tests)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.LocateEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(Int64 entryIndex)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(ZipEntry entry)
   at MHLab.Patch.Core.Compressing.ZipCompressor.ExtractZipFile(String archiveFilenameIn, String password, String outFolder)
   at MHLab.Patch.Core.Compressing.Compressor.Decompress(String folderWhereDecompress, String inputFile, String password)
   at MHLab.Patch.Core.Client.Updater.DecompressPatch(PatchDefinition definition)
   at MHLab.Patch.Core.Client.Updater.PerformUpdate(PatchDefinition definition)
   at MHLab.Patch.Core.Client.Updater.Update()
   at MHLab.Patch.Core.Client.Runners.UpdateRunner.Update()
   at MHLab.Patch.Core.Client.UpdatingContext.Update()
   at MHLab.Patch.Launcher.Wpf.MainWindow.CheckForUpdates()
ICSharpCode.SharpZipLib.Zip.ZipException: Wrong local header signature @3
   at ICSharpCode.SharpZipLib.Zip.ZipFile.TestLocalHeader(ZipEntry entry, HeaderTest tests)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.LocateEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(Int64 entryIndex)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(ZipEntry entry)
   at MHLab.Patch.Core.Compressing.ZipCompressor.ExtractZipFile(String archiveFilenameIn, String password, String outFolder)
   at MHLab.Patch.Core.Compressing.Compressor.Decompress(String folderWhereDecompress, String inputFile, String password)
   at MHLab.Patch.Core.Client.Updater.DecompressPatch(PatchDefinition definition)
   at MHLab.Patch.Core.Client.Updater.PerformUpdate(PatchDefinition definition)
   at MHLab.Patch.Core.Client.Updater.Update()
   at MHLab.Patch.Core.Client.Runners.UpdateRunner.Update()
   at MHLab.Patch.Core.Client.UpdatingContext.Update()
   at MHLab.Patch.Launcher.Wpf.MainWindow.CheckForUpdates()`

**Comment by emanzione** [comment]
Sorry for the late reply, I'm tackling all the issues in this last period.
This sounds like a broken/corrupted file. Not sure if this has been solved or if this happens frequently (this is the first time I read of it), but I could try to introduce a sort of verification step on the Admin side, right after the patch processing. This should alert the developer if something is wrong with the patch.

Let me know your thoughts.
